import { Router, Response } from 'express';
import pool from '../database/db';
import { authenticateToken, AuthRequest } from '../middleware/auth';
// Pure CommonJS policy is deliberately dependency-free and unit-tested with node:test.
const { normalizeObservation, assertTransition } = require('../domain/investigationPolicy');
const router=Router(); const tenant=(req:AuthRequest)=>`user:${req.user!.id}`;
router.use(authenticateToken);
router.post('/sites',async(req:AuthRequest,res:Response)=>{if(!['admin','analyst'].includes(req.user!.role||''))return res.status(403).json({error:'analyst role required'});const {externalId,name,geometryReference}=req.body;if(!externalId||!name)return res.status(400).json({error:'externalId and name required'});const r=await pool.query(`INSERT INTO monitored_sites(tenant_id,external_id,name,geometry_reference,created_by)VALUES($1,$2,$3,$4,$5)ON CONFLICT(tenant_id,external_id)DO UPDATE SET name=EXCLUDED.name,geometry_reference=EXCLUDED.geometry_reference RETURNING *`,[tenant(req),externalId,name,geometryReference||null,req.user!.id]);return res.status(201).json(r.rows[0]);});
router.post('/devices',async(req:AuthRequest,res:Response)=>{if(!['admin','analyst'].includes(req.user!.role||''))return res.status(403).json({error:'analyst role required'});const {siteId,externalId,calibrationVersion,calibrationDueAt,credentialFingerprint}=req.body;if(!siteId||!externalId||!calibrationVersion||!credentialFingerprint)return res.status(400).json({error:'siteId, externalId, calibrationVersion and credentialFingerprint required'});const site=await pool.query('SELECT id FROM monitored_sites WHERE id=$1 AND tenant_id=$2',[siteId,tenant(req)]);if(!site.rowCount)return res.status(400).json({error:'site not found in tenant'});const r=await pool.query(`INSERT INTO monitored_devices(tenant_id,site_id,external_id,calibration_version,calibration_due_at,credential_fingerprint)VALUES($1,$2,$3,$4,$5,$6)ON CONFLICT(tenant_id,external_id)DO UPDATE SET calibration_version=EXCLUDED.calibration_version,calibration_due_at=EXCLUDED.calibration_due_at,credential_fingerprint=EXCLUDED.credential_fingerprint RETURNING *`,[tenant(req),siteId,externalId,calibrationVersion,calibrationDueAt||null,credentialFingerprint]);return res.status(201).json(r.rows[0]);});
router.post('/observations',async(req:AuthRequest,res:Response)=>{try{const normalized=normalizeObservation(req.body);if(!req.body.idempotencyKey)return res.status(400).json({error:'idempotencyKey required'});const device=await pool.query(`SELECT d.calibration_version,d.active,d.calibration_due_at,d.credential_fingerprint,s.external_id AS site_external_id FROM monitored_devices d JOIN monitored_sites s ON s.id=d.site_id AND s.tenant_id=d.tenant_id WHERE d.tenant_id=$1 AND d.external_id=$2`,[tenant(req),normalized.deviceId]);if(!device.rowCount||!device.rows[0].active||device.rows[0].credential_fingerprint!==req.header('x-device-fingerprint'))return res.status(400).json({error:'active authenticated device registration required'});if(device.rows[0].site_external_id!==normalized.siteId)return res.status(409).json({error:'device is not registered to supplied site'});if(device.rows[0].calibration_version!==normalized.calibrationVersion|| (device.rows[0].calibration_due_at && Date.parse(device.rows[0].calibration_due_at)<Date.parse(normalized.observedAt)))return res.status(409).json({error:'calibration version mismatch or calibration expired'});const r=await pool.query(`INSERT INTO governed_observations(tenant_id,site_external_id,device_external_id,source_id,observed_at,value,unit,calibration_version,outlier,idempotency_key)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)ON CONFLICT(tenant_id,idempotency_key)DO UPDATE SET idempotency_key=EXCLUDED.idempotency_key RETURNING *`,[tenant(req),normalized.siteId,normalized.deviceId,normalized.sourceId,normalized.observedAt,normalized.value,normalized.unit,normalized.calibrationVersion,normalized.outlier,req.body.idempotencyKey]);await pool.query(`INSERT INTO environmental_custody_audit(tenant_id,observation_id,actor_id,action,details)VALUES($1,$2,$3,'ingested',$4)`,[tenant(req),r.rows[0].id,req.user!.id,{sourceId:normalized.sourceId,calibrationVersion:normalized.calibrationVersion}]);return res.status(201).json(r.rows[0]);}catch(e:any){return res.status(400).json({error:e.message});}});
router.patch('/observations/:id/state',async(req:AuthRequest,res:Response)=>{const c=await pool.connect();try{await c.query('BEGIN');const f=await c.query('SELECT * FROM governed_observations WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[req.params.id,tenant(req)]);if(!f.rowCount)throw new Error('observation not found');const row=f.rows[0];assertTransition(row.state,req.body.state,{role:req.user!.role,correctionReason:req.body.correctionReason});const u=await c.query('UPDATE governed_observations SET state=$1,correction_reason=COALESCE($2,correction_reason),version=version+1 WHERE id=$3 AND tenant_id=$4 AND version=$5 RETURNING *',[req.body.state,req.body.correctionReason,req.params.id,tenant(req),req.body.version]);if(!u.rowCount)throw new Error('version conflict');await c.query(`INSERT INTO environmental_custody_audit(tenant_id,observation_id,actor_id,action,details)VALUES($1,$2,$3,$4,$5)`,[tenant(req),req.params.id,req.user!.id,req.body.state,{reason:req.body.correctionReason||null}]);await c.query('COMMIT');return res.json(u.rows[0]);}catch(e:any){await c.query('ROLLBACK');return res.status(409).json({error:e.message});}finally{c.release();}});
router.post('/observations/:id/investigations',async(req:AuthRequest,res:Response)=>{if(!req.body.thresholdVersion)return res.status(400).json({error:'versioned threshold required'});const o=await pool.query(`SELECT id FROM governed_observations WHERE id=$1 AND tenant_id=$2 AND state='accepted'`,[req.params.id,tenant(req)]);if(!o.rowCount)return res.status(409).json({error:'accepted observation required'});const r=await pool.query(`INSERT INTO environmental_investigations(tenant_id,observation_id,threshold_version,assignee_id)VALUES($1,$2,$3,$4)RETURNING *`,[tenant(req),req.params.id,req.body.thresholdVersion,req.body.assigneeId||req.user!.id]);return res.status(201).json(r.rows[0]);});
router.patch('/investigations/:id',async(req:AuthRequest,res:Response)=>{if(!['admin','analyst'].includes(req.user!.role||''))return res.status(403).json({error:'analyst role required'});const allowed=['alert_open','investigating','analyst_review','closed'];if(!allowed.includes(req.body.state))return res.status(400).json({error:'invalid investigation state'});if(req.body.state==='closed'&&!req.body.reportReference)return res.status(400).json({error:'reportReference required to close'});const r=await pool.query('UPDATE environmental_investigations SET state=$1,report_reference=COALESCE($2,report_reference),assignee_id=COALESCE($3,assignee_id),updated_at=NOW() WHERE id=$4 AND tenant_id=$5 RETURNING *',[req.body.state,req.body.reportReference,req.body.assigneeId,req.params.id,tenant(req)]);if(!r.rowCount)return res.status(404).json({error:'investigation not found'});return res.json(r.rows[0]);});
router.get('/observations/:id/history',async(req:AuthRequest,res:Response)=>{const r=await pool.query('SELECT * FROM environmental_custody_audit WHERE observation_id=$1 AND tenant_id=$2 ORDER BY created_at,id',[req.params.id,tenant(req)]);return res.json(r.rows);});export default router;
